export default {
    products:[{
        _id: '1',
        name:' pulsar',
        category: 'bikes',
        image:'/images/pulsar.jpg',
        price:40000, 
        brand: 'bajaj',
        rating: 4.5,
        numReview: 10,
        countInStock: 0,
    },
    {
        _id: '2',
        name:' appliances',
        category: 'appliances',
        image:'/images/appliances.jpg',
        price:4000,
        brand: 'bajaj',
        rating: 4.4,
        numReview: 5,
        countInStock: 6,
    },
    {
        _id: '3',
        name:' Electronics',
        category: 'Electronics',
        image:'/images/Electronics.jpg',
        price:5000, 
        brand: 'bajaj',
        rating: 4.5,
        numReview: 10,
        countInStock: 6,
    },
    {
        _id: '4',
        name:' Kitchenware',
        category: 'Kitchenware',
        image:'/images/Kitchenware.jpg',
        price:5000, 
        brand: 'bajaj',
        rating: 4.7,
        numReview: 8,
        countInStock: 6,
    },
    { 
        _id: '5',
    name:' Furnitures',
    category: 'Furnitures',
    image:'/images/Furniture.jpg',
    price:53000, 
    brand: 'bajaj',
    rating: 5,
    numReview: 7,
    countInStock: 6,
}
    
]
}